CXX = clang++

SDL_LIB = -lSDL2_image -lSDL2_mixer -lSDL2_ttf `sdl2-config --libs`
SDL_INCLUDE = `sdl2-config --cflags`
CXXFLAGS = -std=c++0x -O2 -g -Wall -fno-exceptions -Weffc++ $(SDL_INCLUDE) -Iinclude 
OBJS = SDL2Version/main.o SDL2Version/CSDL2Renderer.o src/Modules/TitleScreen/Interactor/CTitleScreenInteractor.o \
src/Modules/TitleScreen/Presenter/CTitleScreenPresenter.o src/Modules/TitleScreen/Router/CTitleScreenRouter.o \
src/Modules/TitleScreen/View/CRect.o src/Modules/TitleScreen/View/CPlayButton.o \
src/Modules/TitleScreen/View/CTitleScreenView.o src/Vipper/IRenderer.o src/Vipper/IEntity.o src/Vipper/IView.o \
src/Vipper/IInteractor.o src/Vipper/IPresenter.o src/Vipper/IRouter.o src/Vipper/CLerp.o  \
src/Vipper/CAnimation.o src/Modules/Gameplay/Entities/CColumn.o src/Modules/Gameplay/Entities/CLevel.o \
src/Modules/Gameplay/Entities/CGameSession.o src/Modules/Gameplay/Presenter/CGameplayPresenter.o \
src/Modules/Gameplay/Presenter/CLevelPresenter.o src/Modules/Gameplay/Router/CGameplayRouter.o \
src/Modules/Gameplay/View/CGameplayView.o src/Modules/Gameplay/View/CBlockAnimationHelper.o \
src/Modules/Gameplay/Interactor/CGameplayInteractor.o
LIBS = $(SDL_LIB)
TARGET = blockyfalls

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:   $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
